const copy={
  en:{apps:"Apps",home:"Home",privacy:"Privacy",support:"Support",catalog:"Apps by Aleksandr Katilov",catalogText:"Independent mobile tools built to make everyday progress simpler.",open:"Open app page →",trackerShort:"An Android workout planner and training log.",kicker:"Android fitness app",title:"BetterSet: Gym Workout Tracker",hero:"Build a consistent gym routine with workout scheduling, adjustable reminders, attendance history, and directions to your gym. Log every set, weight, and rep, and follow your progress in one place.",supportButton:"Get support",privacyButton:"Privacy policy",featureTitle:"Built for the gym",f1:"Plan",f1t:"Choose your gym and start a structured workout.",f2:"Track",f2t:"Record exercises, weight, repetitions, and individual sets.",f3:"Improve",f3t:"Review workout history and calendar activity to follow progress.",privacyTitle:"Privacy Policy",effective:"Effective August 4, 2026",pIntro:"BetterSet is designed as a private workout journal. This policy explains what information the app handles and how it is used.",pCollectTitle:"Information the app handles",pCollect:"The app stores workout information you enter, including exercises, sets, repetitions, weights, workout dates, and the selected gym.",pStoreTitle:"Storage",pStore:"Workout data is stored locally on your device. The current version does not require an account and does not upload your training history to our servers.",pShareTitle:"Sharing",pShare:"We do not sell, rent, or share your workout data with advertisers or other third parties.",pControlTitle:"Your control",pControl:"You control the information saved in the app. Removing the app or clearing its local data may permanently delete your workout history.",pChangesTitle:"Changes to this policy",pChanges:"This policy may be updated when the app gains new functionality. The effective date at the top of this page will be updated when changes are made.",pContactTitle:"Contact",pContact:"Questions about privacy can be submitted through the support page.",supportTitle:"Support",supportIntro:"Need help with BetterSet or found a problem? Use the options below.",helpTitle:"Before contacting support",helpText:"Please include your phone model, Android version, what you were doing, and what happened. Screenshots are helpful when available.",contactTitle:"Contact support",contactPending:"A dedicated support email has not been published yet. For now, contact the developer through LinkedIn.",linkedin:"Contact on LinkedIn ↗",back:"Back to Apps",footer:"BetterSet: Gym Workout Tracker · Android app"},
  ru:{apps:"Приложения",home:"Главная",privacy:"Конфиденциальность",support:"Поддержка",catalog:"Приложения Александра Катилова",catalogText:"Независимые мобильные инструменты, которые помогают двигаться вперёд каждый день.",open:"Открыть страницу →",trackerShort:"Android-приложение для планирования и записи тренировок.",kicker:"Фитнес-приложение для Android",title:"BetterSet: Gym Workout Tracker",hero:"Тренируйтесь регулярно: планируйте занятия, настраивайте напоминания, отмечайте посещения и открывайте маршрут до зала. Записывайте подходы, вес и повторения — вся история тренировок и прогресса в одном месте.",supportButton:"Получить поддержку",privacyButton:"Политика конфиденциальности",featureTitle:"Создано для тренировок",f1:"Планируйте",f1t:"Выберите зал и начните структурированную тренировку.",f2:"Записывайте",f2t:"Сохраняйте упражнения, вес, повторения и каждый отдельный подход.",f3:"Прогрессируйте",f3t:"Просматривайте историю и календарь тренировок, чтобы видеть прогресс.",privacyTitle:"Политика конфиденциальности",effective:"Действует с 4 августа 2026 года",pIntro:"BetterSet создан как личный дневник тренировок. Эта политика объясняет, какие данные обрабатывает приложение и как они используются.",pCollectTitle:"Какие данные обрабатываются",pCollect:"Приложение сохраняет введённые вами данные: упражнения, подходы, повторения, вес, даты тренировок и выбранный зал.",pStoreTitle:"Хранение",pStore:"Данные тренировок хранятся локально на вашем устройстве. Текущая версия не требует аккаунта и не загружает историю тренировок на наши серверы.",pShareTitle:"Передача данных",pShare:"Мы не продаём, не сдаём в аренду и не передаём данные тренировок рекламодателям или другим третьим лицам.",pControlTitle:"Ваш контроль",pControl:"Вы контролируете сохранённую в приложении информацию. Удаление приложения или очистка локальных данных может безвозвратно удалить историю тренировок.",pChangesTitle:"Изменения политики",pChanges:"Политика может обновляться при появлении новых функций. При изменениях дата в верхней части страницы будет обновлена.",pContactTitle:"Связь",pContact:"Вопросы о конфиденциальности можно отправить через страницу поддержки.",supportTitle:"Поддержка",supportIntro:"Нужна помощь с BetterSet или вы нашли ошибку? Используйте варианты ниже.",helpTitle:"Перед обращением",helpText:"Укажите модель телефона, версию Android, что вы делали и что произошло. Если возможно, приложите снимок экрана.",contactTitle:"Связаться с поддержкой",contactPending:"Отдельный email поддержки пока не опубликован. Сейчас можно связаться с разработчиком через LinkedIn.",linkedin:"Написать в LinkedIn ↗",back:"Назад к приложениям",footer:"BetterSet: Gym Workout Tracker · приложение для Android"}
};
Object.assign(copy.en,{screenshotsKicker:"Inside the app",screenshotsTitle:"See every workout at a glance",screenHome:"Dashboard and weekly progress",screenAwards:"Awards and training milestones",screenPrograms:"Ready-made workout programs"});
Object.assign(copy.ru,{screenshotsKicker:"Внутри приложения",screenshotsTitle:"Вся тренировка перед глазами",screenHome:"Главный экран и прогресс за неделю",screenAwards:"Награды и достижения",screenPrograms:"Готовые программы тренировок"});
function setLang(lang){document.documentElement.lang=lang;document.querySelectorAll('[data-t]').forEach(el=>{const value=copy[lang][el.dataset.t];if(value!==undefined)el.textContent=value});document.querySelectorAll('[data-en][data-ru]').forEach(el=>{el.textContent=el.dataset[lang]});document.querySelectorAll('[data-lang]').forEach(b=>{const on=b.dataset.lang===lang;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});localStorage.setItem('apps-language',lang)}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));setLang(localStorage.getItem('apps-language')||'en');

const carousel=document.querySelector('[data-carousel]');
if(carousel){
  const slides=[...carousel.querySelectorAll('.screenshot-slide')];
  const current=document.querySelector('[data-carousel-current]');
  let active=0;
  const show=index=>{active=(index+slides.length)%slides.length;const slide=slides[active];const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;carousel.scrollTo({left:slide.offsetLeft-(carousel.clientWidth-slide.clientWidth)/2,behavior:reduce?'auto':'smooth'});if(current)current.textContent=String(active+1)};
  document.querySelector('[data-carousel-prev]')?.addEventListener('click',()=>show(active-1));
  document.querySelector('[data-carousel-next]')?.addEventListener('click',()=>show(active+1));
  carousel.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'){event.preventDefault();show(active-1)}if(event.key==='ArrowRight'){event.preventDefault();show(active+1)}});
  const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;active=slides.indexOf(visible.target);if(current)current.textContent=String(active+1)},{root:carousel,threshold:[.55,.7,.85]});
  slides.forEach(slide=>observer.observe(slide));
}
